# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68976ef9e46bfbf4093e94221c974e7c85d49336489c2e9ed694a6c2dbda71a368b35f5161c2f5eb01be7439626e867fae6064404aad4c498dad36287230f690

test:
  secret_key_base: c39f02f7089ab156273fd07d1ea0a8d20099beb234f11746be1f8ba91ded67f4934ea0232004208da080a78cb727fe54b7d9357ebe8bde040a90100b6057f462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
